name: 'MC Media'
description: "A recipe for configuring media on a Drupal site."
type: 'Media'

recipes:
  - core/recipes/audio_media_type
  - core/recipes/document_media_type
  - core/recipes/image_media_type
  - core/recipes/local_video_media_type
  - core/recipes/remote_video_media_type

install:
  - focal_point

config:
  strict: false
