name: 'MC Base'
description: "A recipe for kickstarting a new Drupal 11 project."
type: 'Site'

install:
# Core
  - block
  - block_content
  - ckeditor5
  - config
  - contextual
  - datetime
  - dblog
  - editor
  - field
  - field_ui
  - filter
  - help
  - image
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - node
  - options
  - path
  - system
  - taxonomy
  - text
  - user
  - views
  - views_ui

# Contrib
  - config_ignore
  - config_pages
  - config_split
  - custom_field
  - field_group
  - field_widget_add_more
  - maxlength
  - menu_block
  - nomarkup
  - pathauto
  - ui_icons
  - ui_icons_field
  - webform
  - webform_ui
  - vite

# Theming
  - components
  - custom_field_graphql
  - graphql
  - graphql_compose
  - graphql_compose_image_style
  - graphql_compose_menus
  - graphql_compose_routes
  - graphql_twig
  - twig_tweak

# Admin experience
  - admin_toolbar
  - admin_toolbar_tools
  - gin
  - gin_login
  - gin_toolbar
  - gin_type_tray
  - type_tray

# Custom
  - mc_custom
  - mc_icons
  - mc_theme

config:
  strict: false
  actions:
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'mc_theme'
    graphql_twig.settings:
      simple_config_update:
        graphql_server_id: 'graphql_compose_server'
