name: 'MC Alerts'
description: "Provides sitewide alert functionality for a Drupal site."

install:
  - config_pages
  - pathauto
  - sitewide_alert
  - sitewide_alert_block
  - mc_alerts
  - nomarkup
  - ui_icons_field

config:
  strict: false
  actions:
    pathauto.settings:
      simple_config_update:
        enabled_entity_types:
          - sitewide_alert
