name: 'MC Content'
description: "A recipe for configuring media on a Drupal site."
type: 'Content'

recipes:
  - mc_editorial
  - mc_media

install:
  - address
  - better_exposed_filters
  - custom_field
  - entity_reference_revisions
  - entity_usage
  - field_widget_add_more
  - inline_entity_form
  - layout_builder
  - maxlength
  - nomarkup
  - office_hours
  - paragraphs
  - paragraphs_ee
  - paragraphs_features
  - paragraphs_library
  - schemadotorg
  - schemadotorg_address
  - schemadotorg_custom_field
  - schemadotorg_jsonld
  - schemadotorg_media
  - schemadotorg_node
  - schemadotorg_office_hours
  - schemadotorg_paragraphs
  - schemadotorg_smart_date
  - schemadotorg_taxonomy
  - selective_better_exposed_filters
  - smart_date
  - smart_date_recur
  - term_reference_tree
  - taxonomy
  - telephone
  - ui_icons_field
  - ui_icons_library
  - ui_icons_picker

config:
  strict: false
